package vista;

/**
 *
 * @author inici4rsesi0n
 */
public class FCTP_Asignaturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FCTPClass2
     */
    public FCTP_Asignaturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtComunicacion = new javax.swing.JTextField();
        txtDocenteComu = new javax.swing.JTextField();
        btnIniciarSesion3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtArte = new javax.swing.JTextField();
        txtDocenteArte = new javax.swing.JTextField();
        btnIniciarSesion4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtIngles = new javax.swing.JTextField();
        txtDocenteIngles = new javax.swing.JTextField();
        btnIniciarSesion5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtCienciaYTecnologia = new javax.swing.JTextField();
        txtDocenteCyTecno = new javax.swing.JTextField();
        btnIniciarSesion6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtTutoria = new javax.swing.JTextField();
        txtDocenteTutor = new javax.swing.JTextField();
        btnIniciarSesion7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtPersonalSocial = new javax.swing.JTextField();
        txtDocentePSocial = new javax.swing.JTextField();
        btnIniciarSesion8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtEducacionFisica = new javax.swing.JTextField();
        txtDocenteEFisica = new javax.swing.JTextField();
        btnIniciarSesion9 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtMatematica = new javax.swing.JTextField();
        txtDocenteMate = new javax.swing.JTextField();
        btnIniciarSesion10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtEducacionReligiosa = new javax.swing.JTextField();
        txtDocenteEReligiosa = new javax.swing.JTextField();
        btnIniciarSesion11 = new javax.swing.JButton();

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Actividades ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 102, 255));
        jLabel30.setText("2027 - 1er Bimestre Marzo (Actual)");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel31.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 153));
        jLabel31.setText("Mis Cursos");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("Mis Cursos");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 0, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtComunicacion.setBackground(new java.awt.Color(204, 204, 204));
        txtComunicacion.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtComunicacion.setForeground(new java.awt.Color(0, 0, 0));
        txtComunicacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtComunicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteComu.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteComu.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteComu.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteComu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteComu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion3.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion3.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion3.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion3.setText("INGRESAR");
        btnIniciarSesion3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtComunicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteComu))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtComunicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteComu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 110));

        jPanel4.setBackground(new java.awt.Color(102, 0, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtArte.setBackground(new java.awt.Color(204, 204, 204));
        txtArte.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtArte.setForeground(new java.awt.Color(0, 0, 0));
        txtArte.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtArte.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteArte.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteArte.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteArte.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteArte.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteArte.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        txtDocenteArte.addActionListener(this::txtDocenteArteActionPerformed);

        btnIniciarSesion4.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion4.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion4.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion4.setText("INGRESAR");
        btnIniciarSesion4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtArte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteArte))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtArte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteArte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 110));

        jPanel5.setBackground(new java.awt.Color(102, 0, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtIngles.setBackground(new java.awt.Color(204, 204, 204));
        txtIngles.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtIngles.setForeground(new java.awt.Color(0, 0, 0));
        txtIngles.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIngles.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteIngles.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteIngles.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteIngles.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteIngles.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteIngles.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion5.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion5.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion5.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion5.setText("INGRESAR");
        btnIniciarSesion5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteIngles))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, 110));

        jPanel6.setBackground(new java.awt.Color(102, 0, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtCienciaYTecnologia.setBackground(new java.awt.Color(204, 204, 204));
        txtCienciaYTecnologia.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtCienciaYTecnologia.setForeground(new java.awt.Color(0, 0, 0));
        txtCienciaYTecnologia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCienciaYTecnologia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteCyTecno.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteCyTecno.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteCyTecno.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteCyTecno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteCyTecno.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion6.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion6.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion6.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion6.setText("INGRESAR");
        btnIniciarSesion6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtCienciaYTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteCyTecno))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCienciaYTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteCyTecno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 250, 110));

        jPanel7.setBackground(new java.awt.Color(102, 0, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtTutoria.setBackground(new java.awt.Color(204, 204, 204));
        txtTutoria.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtTutoria.setForeground(new java.awt.Color(0, 0, 0));
        txtTutoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTutoria.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteTutor.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteTutor.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteTutor.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteTutor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteTutor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion7.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion7.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion7.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion7.setText("INGRESAR");
        btnIniciarSesion7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtTutoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteTutor))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTutoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 250, 110));

        jPanel8.setBackground(new java.awt.Color(102, 0, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtPersonalSocial.setBackground(new java.awt.Color(204, 204, 204));
        txtPersonalSocial.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtPersonalSocial.setForeground(new java.awt.Color(0, 0, 0));
        txtPersonalSocial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPersonalSocial.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocentePSocial.setBackground(new java.awt.Color(204, 204, 204));
        txtDocentePSocial.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocentePSocial.setForeground(new java.awt.Color(0, 0, 0));
        txtDocentePSocial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocentePSocial.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion8.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion8.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion8.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion8.setText("INGRESAR");
        btnIniciarSesion8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtPersonalSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocentePSocial))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPersonalSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocentePSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 250, 110));

        jPanel9.setBackground(new java.awt.Color(102, 0, 255));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtEducacionFisica.setBackground(new java.awt.Color(204, 204, 204));
        txtEducacionFisica.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtEducacionFisica.setForeground(new java.awt.Color(0, 0, 0));
        txtEducacionFisica.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEducacionFisica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteEFisica.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteEFisica.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteEFisica.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteEFisica.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteEFisica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion9.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion9.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion9.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion9.setText("INGRESAR");
        btnIniciarSesion9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtEducacionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteEFisica))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEducacionFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteEFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 250, 110));

        jPanel10.setBackground(new java.awt.Color(102, 0, 255));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtMatematica.setBackground(new java.awt.Color(204, 204, 204));
        txtMatematica.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtMatematica.setForeground(new java.awt.Color(0, 0, 0));
        txtMatematica.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMatematica.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteMate.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteMate.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteMate.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteMate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteMate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion10.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion10.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion10.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion10.setText("INGRESAR");
        btnIniciarSesion10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtMatematica, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteMate))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMatematica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 110));

        jLabel33.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 102, 255));
        jLabel33.setText("2027 - 1er Bimestre Marzo (Actual)");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel12.setBackground(new java.awt.Color(102, 0, 255));
        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 255), null, null));

        txtEducacionReligiosa.setBackground(new java.awt.Color(204, 204, 204));
        txtEducacionReligiosa.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtEducacionReligiosa.setForeground(new java.awt.Color(0, 0, 0));
        txtEducacionReligiosa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEducacionReligiosa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDocenteEReligiosa.setBackground(new java.awt.Color(204, 204, 204));
        txtDocenteEReligiosa.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        txtDocenteEReligiosa.setForeground(new java.awt.Color(0, 0, 0));
        txtDocenteEReligiosa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDocenteEReligiosa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        btnIniciarSesion11.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciarSesion11.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnIniciarSesion11.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion11.setText("INGRESAR");
        btnIniciarSesion11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(txtEducacionReligiosa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDocenteEReligiosa))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEducacionReligiosa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtDocenteEReligiosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocenteArteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocenteArteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocenteArteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion10;
    private javax.swing.JButton btnIniciarSesion11;
    private javax.swing.JButton btnIniciarSesion3;
    private javax.swing.JButton btnIniciarSesion4;
    private javax.swing.JButton btnIniciarSesion5;
    private javax.swing.JButton btnIniciarSesion6;
    private javax.swing.JButton btnIniciarSesion7;
    private javax.swing.JButton btnIniciarSesion8;
    private javax.swing.JButton btnIniciarSesion9;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTextField txtArte;
    public javax.swing.JTextField txtCienciaYTecnologia;
    public javax.swing.JTextField txtComunicacion;
    public javax.swing.JTextField txtDocenteArte;
    public javax.swing.JTextField txtDocenteComu;
    public javax.swing.JTextField txtDocenteCyTecno;
    public javax.swing.JTextField txtDocenteEFisica;
    public javax.swing.JTextField txtDocenteEReligiosa;
    public javax.swing.JTextField txtDocenteIngles;
    public javax.swing.JTextField txtDocenteMate;
    public javax.swing.JTextField txtDocentePSocial;
    public javax.swing.JTextField txtDocenteTutor;
    public javax.swing.JTextField txtEducacionFisica;
    public javax.swing.JTextField txtEducacionReligiosa;
    public javax.swing.JTextField txtIngles;
    public javax.swing.JTextField txtMatematica;
    public javax.swing.JTextField txtPersonalSocial;
    public javax.swing.JTextField txtTutoria;
    // End of variables declaration//GEN-END:variables
}
