/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author inici4rsesi0n
 */
public class FMenuRegistros extends javax.swing.JInternalFrame {

    /**
     * Creates new form FMenuRegistros1
     */
    public FMenuRegistros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMantenimiento = new javax.swing.JMenu();
        mniEstudiantes = new javax.swing.JMenuItem();
        mniDocentes = new javax.swing.JMenuItem();
        mniSalones = new javax.swing.JMenuItem();
        mniAsignaturas = new javax.swing.JMenuItem();
        mniHorarios = new javax.swing.JMenuItem();
        mniGestionAsignaturas = new javax.swing.JMenuItem();

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Menú Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 2, 13), new java.awt.Color(51, 102, 255))); // NOI18N
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 153));
        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N

        mnuMantenimiento.setText("Mantenimiento");

        mniEstudiantes.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        mniEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        mniEstudiantes.setText("Estudiantes");
        mnuMantenimiento.add(mniEstudiantes);

        mniDocentes.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        mniDocentes.setForeground(new java.awt.Color(255, 255, 255));
        mniDocentes.setText("Docentes");
        mniDocentes.addActionListener(this::mniDocentesActionPerformed);
        mnuMantenimiento.add(mniDocentes);

        mniSalones.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        mniSalones.setForeground(new java.awt.Color(255, 255, 255));
        mniSalones.setText("Salones");
        mnuMantenimiento.add(mniSalones);

        mniAsignaturas.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        mniAsignaturas.setForeground(new java.awt.Color(255, 255, 255));
        mniAsignaturas.setText("Asignaturas");
        mnuMantenimiento.add(mniAsignaturas);

        mniHorarios.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        mniHorarios.setForeground(new java.awt.Color(255, 255, 255));
        mniHorarios.setText("Horarios");
        mnuMantenimiento.add(mniHorarios);

        mniGestionAsignaturas.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        mniGestionAsignaturas.setForeground(new java.awt.Color(255, 255, 255));
        mniGestionAsignaturas.setText("Gestión Asignaturas");
        mnuMantenimiento.add(mniGestionAsignaturas);

        jMenuBar1.add(mnuMantenimiento);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDocentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDocentesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegresar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuItem mniAsignaturas;
    public javax.swing.JMenuItem mniDocentes;
    public javax.swing.JMenuItem mniEstudiantes;
    public javax.swing.JMenuItem mniGestionAsignaturas;
    public javax.swing.JMenuItem mniHorarios;
    public javax.swing.JMenuItem mniSalones;
    public javax.swing.JMenu mnuMantenimiento;
    // End of variables declaration//GEN-END:variables
}
