/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author inici4rsesi0n
 */
public class FPortalCTP extends javax.swing.JInternalFrame {

    /**
     * Creates new form FPortalCTP1
     */
    public FPortalCTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbxSalon = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEliminarMatricula = new javax.swing.JButton();
        btnGuardarMatricula = new javax.swing.JButton();
        btnRegistrarMatricula = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTutorAsignado = new javax.swing.JTextField();
        txtMaxAlumnos = new javax.swing.JTextField();
        txtGrado = new javax.swing.JTextField();
        txtCanAlumnos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHorario = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaEstudiantes = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Matricula Estudiantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 13), new java.awt.Color(51, 102, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxSalon.setBackground(new java.awt.Color(204, 204, 204));
        cbxSalon.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxSalon.setForeground(new java.awt.Color(0, 0, 0));
        cbxSalon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Salón", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(cbxSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 40));

        jLabel32.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 102, 255));
        jLabel32.setText("Alumno");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        txtAlumno.setEditable(false);
        txtAlumno.setBackground(new java.awt.Color(204, 204, 204));
        txtAlumno.setForeground(new java.awt.Color(0, 0, 0));
        txtAlumno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAlumno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jPanel2.add(txtAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 30));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        txtCodigo.addActionListener(this::txtCodigoActionPerformed);
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        jLabel33.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 102, 255));
        jLabel33.setText("Alumno");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Código CTP ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Código CTP ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        btnEliminarMatricula.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarMatricula.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnEliminarMatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMatricula.setText("Eliminar Matricula");
        btnEliminarMatricula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 0, 51), null, null));
        jPanel2.add(btnEliminarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, 50));

        btnGuardarMatricula.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardarMatricula.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnGuardarMatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarMatricula.setText("Guardar Matricula");
        btnGuardarMatricula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        jPanel2.add(btnGuardarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 50));

        btnRegistrarMatricula.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarMatricula.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnRegistrarMatricula.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarMatricula.setText("Registrar Matricula");
        btnRegistrarMatricula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        jPanel2.add(btnRegistrarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 50));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 100, -1));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTutorAsignado.setEditable(false);
        txtTutorAsignado.setBackground(new java.awt.Color(204, 204, 204));
        txtTutorAsignado.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtTutorAsignado.setForeground(new java.awt.Color(0, 0, 0));
        txtTutorAsignado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTutorAsignado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Tutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.add(txtTutorAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 40));

        txtMaxAlumnos.setEditable(false);
        txtMaxAlumnos.setBackground(new java.awt.Color(204, 204, 204));
        txtMaxAlumnos.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtMaxAlumnos.setForeground(new java.awt.Color(0, 0, 0));
        txtMaxAlumnos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaxAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Max Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.add(txtMaxAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 100, 40));

        txtGrado.setEditable(false);
        txtGrado.setBackground(new java.awt.Color(204, 204, 204));
        txtGrado.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtGrado.setForeground(new java.awt.Color(0, 0, 0));
        txtGrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Grado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 40));

        txtCanAlumnos.setEditable(false);
        txtCanAlumnos.setBackground(new java.awt.Color(204, 204, 204));
        txtCanAlumnos.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtCanAlumnos.setForeground(new java.awt.Color(0, 0, 0));
        txtCanAlumnos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCanAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.add(txtCanAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 90, 40));

        tblHorario.setBackground(new java.awt.Color(255, 255, 255));
        tblHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblHorario.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        tblHorario.setForeground(new java.awt.Color(0, 0, 0));
        tblHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHorario.setPreferredSize(new java.awt.Dimension(800, 150));
        tblHorario.setRowHeight(30);
        jScrollPane3.setViewportView(tblHorario);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 370));

        tblListaEstudiantes.setBackground(new java.awt.Color(255, 255, 255));
        tblListaEstudiantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblListaEstudiantes.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        tblListaEstudiantes.setForeground(new java.awt.Color(0, 0, 0));
        tblListaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaEstudiantes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 490, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnEliminarMatricula;
    public javax.swing.JButton btnGuardarMatricula;
    public javax.swing.JButton btnRegistrarMatricula;
    public javax.swing.JComboBox<String> cbxSalon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblHorario;
    public javax.swing.JTable tblListaEstudiantes;
    public javax.swing.JTextField txtAlumno;
    public javax.swing.JTextField txtCanAlumnos;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtGrado;
    public javax.swing.JTextField txtMaxAlumnos;
    public javax.swing.JTextField txtTutorAsignado;
    // End of variables declaration//GEN-END:variables
}
