/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author inici4rsesi0n
 */
public class FRHorarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRHorarios1
     */
    public FRHorarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordeLogin = new javax.swing.JPanel();
        cbxHora = new javax.swing.JComboBox<>();
        cbxGrado = new javax.swing.JComboBox<>();
        cbxSalon = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        cbxDocente = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        cbxDia = new javax.swing.JComboBox<>();
        cbxAPD12 = new javax.swing.JComboBox<>();
        cbxAsignatura = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAreaInfo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRegistroHorario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        BordeLogin.setBackground(new java.awt.Color(255, 255, 255));
        BordeLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Registro Horarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 3, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        BordeLogin.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        BordeLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxHora.setBackground(new java.awt.Color(204, 204, 204));
        cbxHora.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxHora.setForeground(new java.awt.Color(0, 0, 0));
        cbxHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 40));

        cbxGrado.setBackground(new java.awt.Color(204, 204, 204));
        cbxGrado.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxGrado.setForeground(new java.awt.Color(0, 0, 0));
        cbxGrado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 40));

        cbxSalon.setBackground(new java.awt.Color(204, 204, 204));
        cbxSalon.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxSalon.setForeground(new java.awt.Color(0, 0, 0));
        cbxSalon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Salón", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        cbxSalon.addActionListener(this::cbxSalonActionPerformed);
        BordeLogin.add(cbxSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, 40));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 153));
        btnRegistrar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 255), null, null));
        BordeLogin.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, 30));

        cbxDocente.setBackground(new java.awt.Color(204, 204, 204));
        cbxDocente.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxDocente.setForeground(new java.awt.Color(0, 0, 0));
        cbxDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Docente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BordeLogin.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        cbxDia.setBackground(new java.awt.Color(204, 204, 204));
        cbxDia.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxDia.setForeground(new java.awt.Color(0, 0, 0));
        cbxDia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Día", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 40));

        cbxAPD12.setBackground(new java.awt.Color(204, 204, 204));
        cbxAPD12.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxAPD12.setForeground(new java.awt.Color(0, 0, 0));
        cbxAPD12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));
        cbxAPD12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Día", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxAPD12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 40));

        cbxAsignatura.setBackground(new java.awt.Color(204, 204, 204));
        cbxAsignatura.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxAsignatura.setForeground(new java.awt.Color(0, 0, 0));
        cbxAsignatura.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Asignatura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 50));

        btnRefrescar.setBackground(new java.awt.Color(0, 204, 51));
        btnRefrescar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 50));

        txaAreaInfo.setBackground(new java.awt.Color(204, 204, 204));
        txaAreaInfo.setColumns(20);
        txaAreaInfo.setRows(5);
        txaAreaInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(txaAreaInfo);

        tblRegistroHorario.setBackground(new java.awt.Color(51, 102, 255));
        tblRegistroHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblRegistroHorario.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        tblRegistroHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistroHorario.setPreferredSize(new java.awt.Dimension(800, 150));
        tblRegistroHorario.setRowHeight(30);
        jScrollPane3.setViewportView(tblRegistroHorario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BordeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BordeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSalonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BordeLogin;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxAPD12;
    public javax.swing.JComboBox<String> cbxAsignatura;
    public javax.swing.JComboBox<String> cbxDia;
    public javax.swing.JComboBox<String> cbxDocente;
    public javax.swing.JComboBox<String> cbxGrado;
    public javax.swing.JComboBox<String> cbxHora;
    public javax.swing.JComboBox<String> cbxSalon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblRegistroHorario;
    public javax.swing.JTextArea txaAreaInfo;
    // End of variables declaration//GEN-END:variables
}
