/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author inici4rsesi0n
 */
public class FRSalones extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRSalones1
     */
    public FRSalones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordeLogin = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtSalon = new javax.swing.JTextField();
        cbxTutor = new javax.swing.JComboBox<>();
        txtAlumnosMAX = new javax.swing.JTextField();
        cbxGrado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRegistroSalones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        BordeLogin.setBackground(new java.awt.Color(255, 255, 255));
        BordeLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Registro Salones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 3, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        BordeLogin.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        BordeLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BordeLogin.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 153));
        btnRegistrar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 255), null, null));
        BordeLogin.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 30));

        txtSalon.setBackground(new java.awt.Color(204, 204, 204));
        txtSalon.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtSalon.setForeground(new java.awt.Color(0, 0, 0));
        txtSalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalon.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Salón", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        txtSalon.addActionListener(this::txtSalonActionPerformed);
        BordeLogin.add(txtSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, 40));

        cbxTutor.setBackground(new java.awt.Color(204, 204, 204));
        cbxTutor.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxTutor.setForeground(new java.awt.Color(0, 0, 0));
        cbxTutor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 40));

        txtAlumnosMAX.setBackground(new java.awt.Color(204, 204, 204));
        txtAlumnosMAX.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtAlumnosMAX.setForeground(new java.awt.Color(0, 0, 0));
        txtAlumnosMAX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlumnosMAX.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Alumnos MAX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        txtAlumnosMAX.addActionListener(this::txtAlumnosMAXActionPerformed);
        BordeLogin.add(txtAlumnosMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 40));

        cbxGrado.setBackground(new java.awt.Color(204, 204, 204));
        cbxGrado.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cbxGrado.setForeground(new java.awt.Color(0, 0, 0));
        cbxGrado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        BordeLogin.add(cbxGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 51));
        btnLimpiar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 50));

        btnRefrescar.setBackground(new java.awt.Color(0, 204, 51));
        btnRefrescar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 0), null, null));
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 50));

        tblRegistroSalones.setBackground(new java.awt.Color(51, 102, 255));
        tblRegistroSalones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblRegistroSalones.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        tblRegistroSalones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblRegistroSalones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BordeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BordeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalonActionPerformed

    private void txtAlumnosMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlumnosMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlumnosMAXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BordeLogin;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JComboBox<String> cbxGrado;
    public javax.swing.JComboBox<String> cbxTutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblRegistroSalones;
    public javax.swing.JTextField txtAlumnosMAX;
    public javax.swing.JTextField txtSalon;
    // End of variables declaration//GEN-END:variables
}
